### ISSUE TITLE
T01: Project Setup

### ISSUE THREAD

**Issue by berk-karademir** [berk-karademir/BekoStore#1]
- [x] Create github repo
- [x] Create React Project via [Vite](https://vitejs.dev/guide/)
- [x] Install all dependencies
    - [x] #3
    - [x] React Router v5
    - [x] Tailwind
    - [x] Axios
    - [x] Toastify
    - [x] Icon Library - (https://lucide.dev/guide/packages/lucide-react)
- [x] Deploy your project to Vercel/Render/Netlify

Tip: Here is a Youtube Playlist [Workintech E-Comm Projesi Doping](https://youtube.com/playlist?list=PL-w1xOwMMQ1PTMXidBINRj9diBko1X86U&feature=shared)  for tips and tricks, relevant the project.

**Comment by berk-karademir** [comment]
@gokhanozdemir
dependencies installed & project deployed on vercel

**Comment by gokhanozdemir** [comment]
Task'ını done'a çekebilirsin.

**Comment by berk-karademir** [comment]
![ss](https://github.com/user-attachments/assets/40fde1a1-932e-4b08-929b-f5da7d0e77a9)
Başka bir şey yapmama gerek var mı?

**Comment by gokhanozdemir** [comment]
Adam taskı yaptığının ekran görüntüsünü de gönderdi ya 🚀

**Comment by gokhanozdemir** [comment]
Artık yatıp yarın sabah için dinlenme vakti :D

**Comment by berk-karademir** [comment]
dün done kısmına atmıştım da acaba issue'yla alakalı bir şey de yapmam gerekiyor mu diye merak ettim :)

**Comment by gokhanozdemir** [comment]
Done'a atınca kendi kapanmalı kapanmazsa sağ alttaki "Close" a bas
